languageCode = "en-US"
title = "Guido Percu's Notes"
uglyURLS =  true

relativeURLs = true

publishDir = "public"
pygmentsUseClasses = true

# assetDir = "themes/zettels/assets"

DefaultContentLanguage = "en"

# theme = "zettels"

[outputs]
  home = ["HTML", "JSON"]

[params]
    theme = "red-graphite"
    bear = true
    favicon = "favicon.ico"
    author = "Guido Perc√∫"
    subtitle = "My Garden"

# Enable tags.
[taxonomies]
    tag = "tags"


# Allows rendering the html inside markdown
[markup.goldmark.renderer]
unsafe= true
